services:
  - type: web
    name: my-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: MONGO_URI
        value: your-mongodb-uri
      - key: NODE_ENV
        value: production
